## external : influxdb

influxdb:
  enabled: true
  fullnameOverride: "cb-dragonfly-influxdb"
  database: "cbmon"
  adminUser:
    name: "cbmon"
    pwd: "password"
  persistence:
    enabled: false
    size: "8Gi"
    accessModes: "ReadWriteMany"


## external: kapacitor

kapacitor:
  enabled: true
  nameOverride: "dragonfly-kapacitor"
  envVars:
    #KAPACITOR_INFLUXDB_0_URLS_0: http://cb-dragonfly-influxdb:8086
    KAPACITOR_INFLUXDB_0_USERNAME: cbmon
    KAPACITOR_INFLUXDB_0_PASSWORD: password
  persistence:
    enabled: false
    size: "8Gi"
    accessModes: "ReadWriteMany"
  influxURL: http://cb-dragonfly-influxdb:8086
  #  namespaceOverride: cloud-barista

## external : kafka

kafka:
  enabled: true
  image: wurstmeister/kafka
  imageTag: 2.12-2.4.1
  replicas: 1
  fullnameOverride: "cb-dragonfly-kafka"
  external:
    enabled: true
    dns:
      useInternal: true
      useExternal: true
    servicePort: 9092
    firstListenerPort: 32000
    type: NodePort
  persistence:
    enabled: false
    size: "1Gi"
    accessModes: "ReadWriteMany"
  jmx:
    configMap:
      enabled: false
  prometheus:
    mx:
      enabled: false
    kafka:
      enabled: false
    operator:
      enabled: false
  zookeeper:
    enabled: false
      #     url: "cb-dragonfly-zookeeper:2181"
      #     fullnameOverride: "cb-dragonfly-zookeeper"
      #     port: 2181
  configurationOverrides:
    ADVERTISED_HOST_NAME: cb-dragonfly-kafka
    PORT: 9092
    ADVERTISED_PORT: 32000
    #    advertised.listeners: PLAINTEXT://localhost:9092
    DELETE_TOPIC_ENABLE: "true"
    LOG_RETENTION_HOURS: 1
    # 1 hours (delete logs)
    LOG_RETENTION_BYTES: "524288000"
    # 500 MB
    LOG_SEGMENT_BYTES: "262144000"
    # 250 MB
    LOG_RETENTION_CHECK_INTERVAL_MS: 600000
    # 10 min (check interval)
    MESSAGE_TIMESTAMP_TYPE: LogAppendTime
    LOG_MESSAGE_TIMESTAMP_TYPE: LogAppendTime
    #   LISTENERS: PLAINTEXT://:9092
    zookeeper.connect: "cb-dragonfly-zookeeper:2181"
    zookeeper.connection.timeout.ms: 18000
    zookeeper.session.timeout.ms: 10000

## external : zookeeper

zookeeper:
  enabled: true
  replicaCount: 1
  fullnameOverride: "cb-dragonfly-zookeeper"
  persistence:
    enabled: false
  zookeeper:
   enabled: false
  exporters:
    jmx:
      enabled: false



## cb-dragonfly custom variables
dragonfly:
  rootPath: "/go/src/github.com/cloud-barista/cb-dragonfly"

## chart values
replicaCount: 1

image:
  repository: cloudbaristaorg/cb-dragonfly
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "cb-dragonfly"

serviceAccount:
  create: true
  annotations: {}
  name:

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  restPort: 9090
  grpcPort: 9999
  #monitorPort: 8094

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: cloud-barista.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m

nodeSelector: {}

tolerations: []

affinity: {}
